### ISSUE TITLE
Error in hook, no functionality

### ISSUE THREAD

**Issue by websterguy** [reyzor1991/foundry-vtt-pf2e-reaction#1]
PF2 4.11.2
Foundry 10.291
Reaction Checker 0.1.1

When a token moves, this error is the only thing that happens from this module. No message about AoO is present.
```js
TypeError: Error thrown in hooked function '' for hook 'preUpdateToken'. Cannot read properties of undefined (reading 'find')
    at hooks.js:55:67
    at Array.filter (<anonymous>)
    at hooks.js:55:41
    at Array.forEach (<anonymous>)
    at checkCombatantTriggerAttackOfOpportunity (hooks.js:52:10)
    at Object.fn (hooks.js:115:13)
    at #call (foundry.js:724:20)
    at Hooks.call (foundry.js:706:38)
    at ClientDatabaseBackend._preUpdateDocumentArray (foundry.js:12736:47)
    at async ClientDatabaseBackend._updateEmbeddedDocuments (foundry.js:12661:22)
  ```

**Comment by reyzor1991** [comment]
Fixed in 0.1.2
